### ISSUE TITLE
Annotation dataset Issue

### ISSUE THREAD

**Issue by Aditya183** [leddartech/object_detection_pixell#2]
Hi, I am trying to visualize the annotated images of pixset dataset. While i am trying yo run: python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.py which was given that will help for augmentatio data I couldn't able to get it and facing many issues. Currently I am facing with sync_labels issue. 
How to solve this to visualize the annotation data?
![Screenshot 2021-05-20 140042](https://user-images.githubusercontent.com/55274133/118946365-ee943500-b973-11eb-98f5-b200dabb6dd0.jpg)

Thanks in Advance

**Comment by jeanlucdeziel-leddartech** [comment]
prepare_inserts_data.py is only if you need to train the object detection model.

To visualize the annotations, launch dasview. Then click on the "ech" box next to "pixell_bfc". In the new window, you will see the surface cloud from the pixell. There should be a tab "box3d" that you can click, then a checkbox "pixell_bfc_box3d-deepen".

**Comment by Aditya183** [comment]
Hey thanks for your reply @jeanlucdeziel-leddartech and please confirm me that, to visualise the annotated data, one needs to follow the pionner.das.view right!?
If so, in that case, how can I find check out "pixell_bfc" next to "ech" and find out the steps you have mentioned!?
Kindly guide me as I am very new to this and I am confused.
Thanks!

**Comment by Liveshkumar** [comment]
@Aditya183  check whether u deleted all the zip file 
eg. while downloading the file will be 20200706_162218_part21_4368_7230.zip then u do unzip later then u want to delete this file  20200706_162218_part21_4368_7230.zip from the path 
if u do so means u can fix

**Comment by Aditya183** [comment]
> @Aditya183 check whether u deleted all the zip file
> eg. while downloading the file will be 20200706_162218_part21_4368_7230.zip then u do unzip later then u want to delete this file 20200706_162218_part21_4368_7230.zip from the path
> if u do so means u can fix

Ok, I will check on it and do we need to write any further scripts for proper functioning of the model as I am running it in the colab and my local os is windows

**Comment by Liveshkumar** [comment]
@Aditya183  check whether u given the path for train and test in config file. 
and then i am working with linux so i don't about that sure. 
thanks

**Comment by Aditya183** [comment]
Ok, Thank you so much @Liveshkumar for your time. I will take all your inputs to make sure to follow.
