### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/pixell_to_box3d.py'

### ISSUE THREAD

**Issue by Liveshkumar** [leddartech/object_detection_pixell#3]
(ledderpixset) root:/dataset/object_detection_pixell# python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.py
Traceback (most recent call last):
  File "prepare_inserts_data.py", line 77, in <module>
    with open(args.cfg, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/pixell_to_box3d.py'

the file inside the config is in the format of pixell_to_box3d.yml how the code will run when using the cmd python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.py

can u please explain?

thanks in advance

**Comment by Aditya183** [comment]
> (ledderpixset) root:/dataset/object_detection_pixell# python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.py
> Traceback (most recent call last):
> File "prepare_inserts_data.py", line 77, in
> with open(args.cfg, 'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'configs/pixell_to_box3d.py'
> 
> the file inside the config is in the format of pixell_to_box3d.yml how the code will run when using the cmd python3 prepare_inserts_data.py --cfg=configs/pixell_to_box3d.py
> 
> can u please explain?
> 
> thanks in advance

Hello,
I am facing this issue too, but once plz checkout the path you have given for the "--cfg" and just try once.
I have one issue @Liveshkumar if you passed through it plz help me out with it. Can you visualize the annotated data and have you extracted it!? I am facing issues with it and I couldn't able to visualize the annotated dataset. 
For your kind info I'm running it in Google colab and mine is windows.
Hope for your reply

Thanks!

**Comment by Liveshkumar** [comment]
sorry i cleared the issue instead of --cfg=configs/pixell_to_box3d.py if we give --cfg=configs/pixell_to_box3d.yml it is working well

thanks for your reply @Aditya183

**Comment by Aditya183** [comment]
> sorry i cleared the issue instead of --cfg=configs/pixell_to_box3d.py if we give --cfg=configs/pixell_to_box3d.yml it is working well
> 
> thanks for your reply @Aditya183

Could you help me out with that as still I am facing the issue even I have given --cfg=configs/pixell_to_box3d.yml

**Comment by Liveshkumar** [comment]
@Aditya183  what issue?

**Comment by Aditya183** [comment]
If I am trying to run in my local machine with VS code editor I am facing PyQt issues as it is not supporting the requirement version for this model.

**Comment by Aditya183** [comment]
Hi @Liveshkumar do we need to write a new script for accessing the labeled data?

**Comment by Liveshkumar** [comment]
> Hi @Liveshkumar do we need to write a new script for accessing the labeled data?

@Aditya183  sorry can u explain your question little bit more?

**Comment by Aditya183** [comment]
> > Hi @Liveshkumar do we need to write a new script for accessing the labeled data?
> 
> @Aditya183 sorry can u explain your question little bit more?

I am trying to visualize the labelled data from the given sequences of datasets. How to do that? Do we need to write any script for that?
